version: '3.8'

services:
  db:
    image: postgres:13.3-alpine
    env_file:
      - .env
    expose:
      - 5432
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always

  celery:
    build:
      context: ./backend
      dockerfile: celery_worker.dockerfile
    env_file:
      - .env
    restart: always
    volumes:
      - pictures:/app/pictures
    depends_on:
      - redis

  flower:
    image: mher/flower:1.2
    env_file:
      - .env
    restart: always
    ports:
      - 5555:5555
    depends_on:
      - celery

  app:
    build:
      context: ./backend
      dockerfile: app.dockerfile
    env_file:
      - .env
    command: >
      bash -c "alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0"
    restart: always
    ports:
      - 8000:8000
    volumes:
      - pictures:/app/pictures
    depends_on:
      - db
      - celery

volumes:
  db_data:
  pictures:
